export const data = [
    {
        question: "What is the 'single source of truth' in Redux?",
        option1: "The Reducer",
        option2: "The Store",
        option3: "The Action",
        option4: "The Component",
        ans: 2,
    },
    {
        question: "Which hook is used to access the state from the Redux store?",
        option1: "useDispatch",
        option2: "useState",
        option3: "useSelector",
        option4: "useReducer",
        ans: 3,
    },
    {
        question: "What function is used to send an action to the store?",
        option1: "dispatch()",
        option2: "update()",
        option3: "commit()",
        option4: "send()",
        ans: 1,
    },
    {
        question: "What should a Reducer always be?",
        option1: "An asynchronous function",
        option2: "A class method",
        option3: "A pure function",
        option4: "A global variable",
        ans: 3,
    },
    {
        question: "In Redux Toolkit, which function creates actions and reducers simultaneously?",
        option1: "createStore",
        option2: "createAction",
        option3: "createSlice",
        option4: "combineReducers",
        ans: 3,
    },
    {
        question: "What is the purpose of Redux Thunk middleware?",
        option1: "To style components",
        option2: "To handle asynchronous logic",
        option3: "To optimize rendering",
        option4: "To manage local component state",
        ans: 2,
    },
    {
        question: "How do you update the state in a Redux reducer?",
        option1: "By modifying the current state directly",
        option2: "By returning a new state object",
        option3: "By calling state.update()",
        option4: "By using the setState() method",
        ans: 2,
    },
    {
        question: "Which component provides the Redux store to the entire React app?",
        option1: "<BrowserRouter>",
        option2: "<StoreProvider>",
        option3: "<Provider>",
        option4: "<ReduxApp>",
        ans: 3,
    },
    {
        question: "What is an 'Action' in Redux?",
        option1: "A function that changes the state",
        option2: "A plain JavaScript object with a 'type' property",
        option3: "A listener for state changes",
        option4: "A database query",
        ans: 2,
    },
    {
        question: "What does the 'useDispatch' hook return?",
        option1: "The current state",
        option2: "A reference to the dispatch function",
        option3: "An array of all actions",
        option4: "A boolean login status",
        ans: 2,
    }
];
